// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/google/wire"
	"receipt_processor/internal/dbprovider"
	"receipt_processor/internal/logic"
)

// Injectors from wire.go:

// InitializeServer initializes a new server instance.
func InitializeServer() (Server, error) {
	dbDB := db.ProvideCacheDB()
	receiptLogic := logic.NewReceiptLogic(dbDB)
	serverServer := NewServer(receiptLogic)
	return serverServer, nil
}

// wire.go:

// ProviderSet is the Wire provider set for the server.
var ProviderSet = wire.NewSet(db.ProvideCacheDB, logic.NewReceiptLogic, NewServer)
